### ISSUE TITLE
Display Rendering Issue

### ISSUE THREAD

**Issue by SkyeChen-28** [OiCMudkips/marimba#13]
The calendars sometimes block the description box in account history
![image](https://user-images.githubusercontent.com/57053562/67629612-842a1a00-f84e-11e9-81fd-d450d55fc071.png)

**Comment by adklco** [comment]
Hello, is this still an issue for you?

**Comment by SkyeChen-28** [comment]
Yes, but I think it's a client-side issue. I can fix it by changing the size of my system display text to 100% (by default, it is 150%). I asked around and I was the only one with this issue and it can be fixed by changing system settings.
![image](https://user-images.githubusercontent.com/57053562/91667948-61a00780-ead6-11ea-9713-3a8ebc86d9cd.png)

**Comment by adklco** [comment]
Release 2.3.1.1 has it so that the calendars in Account History don't change size and cover things (the text in the calendar still becomes bigger so the calendar text gets cut off, though).

I don't think this is fully fixable unless we change the type of calendar.

**Comment by SkyeChen-28** [comment]
Hi, reopening this because it's still an issue and I'm told this is fixable.

Edit: I thought creating a new comment would reopen this issue. It didn't 😐
