### ISSUE TITLE
Adding a duplicate member to "Attendance" gives the wrong error message

### ISSUE THREAD

**Issue by SkyeChen-28** [OiCMudkips/marimba#14]
When I add a duplicate member to the current term under the "Attendance" records (under the Membership tab), the error message reads "Too many members in the given term. Please add fewer members."

Reproducing the error:
1. Go to the Membership tab, click the Attendance button.
2. Click "Add Member to Term" and add a member that has already been added to the term
3. It will give the wrong error message

![image](https://user-images.githubusercontent.com/57053562/138210271-7eb28474-c3a3-4c8d-89ef-0abefc2542c3.png)

I have two concerns about this:
1. The error message is wrong, please fix it to "Member already in the current term." or something along those lines. 
2. We have a limit on how many members we can add per term?!!?!?!?! please tell me that it's at least an absurdly high number...

**Comment by adklco** [comment]
Should be resolved. Will provide test build.

**Comment by SkyeChen-28** [comment]
Can confirm that this issue has been resolved. Thanks Nathan!
