### ISSUE TITLE
Feature Request: Ability to remove members from the current term

### ISSUE THREAD

**Issue by SkyeChen-28** [OiCMudkips/marimba#15]
I accidentally added a "Raymond Yeung" who was in the band back in 2014, when I intended to sign up a "Raymond Yeung" who joined the band in Fall 2021. I was unable to remove the old Raymond Yeung. I assume that I would be able to if I exported all data, modified it, and reimported it, but that feels too risky for me to try lol.

**Comment by adklco** [comment]
This feature already exists by selecting a member and hitting the delete key. However, I will make this functionality a bit more obvious.

**Comment by SkyeChen-28** [comment]
Can confirm that this feature works. Thanks again Nathan!
